// Generated by commsdsl2tools_qt v6.3.2

#pragma once

#include <QtCore/QVariantMap>

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace field
{

QVariantMap createProps_clientId(const char* name, bool serHidden = false);

} // namespace field

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
