// Generated by commsdsl2tools_qt v6.3.4

#include "Ctrl.h"

#include "cc_mqttsn/field/Ctrl.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/Radius.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace field
{

namespace
{

struct CtrlMembers
{
    static QVariantMap createProps_radius(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_mqttsn::field::CtrlMembers<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Radius;
        auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_radius(Field::name(), serHidden);
        return props;
    }

    static QVariantMap createProps_reserved(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_mqttsn::field::CtrlMembers<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Reserved;
        return
            cc_tools_qt::property::field::ForField<Field>()
                .name(Field::name())
                .serialisedHidden(serHidden)
                .asMap();
    }
}; // struct CtrlMembers

} // namespace

QVariantMap createProps_ctrl(const char* name, bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::field::Ctrl<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(name)
            .serialisedHidden(serHidden)
            .add(CtrlMembers::createProps_radius(true))
            .add(CtrlMembers::createProps_reserved(true))
            .asMap();
}

} // namespace field

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
