// Generated by commsdsl2tools_qt v8.0.0

#include "Plugin_CC_MQTT_SN.h"

#include "Protocol_CC_MQTT_SN.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace plugin
{

Plugin_CC_MQTT_SN::Plugin_CC_MQTT_SN() :
    Base(Type_Protocol)
{
}

Plugin_CC_MQTT_SN::~Plugin_CC_MQTT_SN() = default;

cc_tools_qt::ToolsProtocolPtr Plugin_CC_MQTT_SN::createProtocolImpl()
{
    return cc_tools_qt::ToolsProtocolPtr(new Protocol_CC_MQTT_SN());
}

} // namespace plugin

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
