// Generated by commsdsl2tools_qt v6.3.3

#pragma once

#include <QtCore/QObject>
#include <QtCore/QtPlugin>
#include "cc_tools_qt/Plugin.h"
#include "cc_tools_qt/Protocol.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace plugin
{

class Plugin_CC_MQTT_SN : public cc_tools_qt::Plugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID "cc.MqttSnProtocolPlugin" FILE "Plugin_CC_MQTT_SN.json")
    Q_INTERFACES(cc_tools_qt::Plugin)

public:
    Plugin_CC_MQTT_SN();
    virtual ~Plugin_CC_MQTT_SN();

private:
    cc_tools_qt::ProtocolPtr m_protocol;
};

} // namespace plugin

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
