// Generated by commsdsl2tools_qt v7.0.2

#include "Protocol_CC_MQTT_SN.h"

#include "cc_tools_qt_plugin/Message/cc_mqttsn/frame/Frame.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace plugin
{

Protocol_CC_MQTT_SN::Protocol_CC_MQTT_SN() :
    Base(std::make_unique<cc_tools_qt_plugin::Message::cc_mqttsn::frame::Frame>())
{
}

Protocol_CC_MQTT_SN::~Protocol_CC_MQTT_SN() = default;

const QString& Protocol_CC_MQTT_SN::nameImpl() const
{
        static const QString Str("CC MQTT-SN");
        return Str;
}

} // namespace plugin

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
