// Generated by commsdsl2tools_qt v7.0.2

#pragma once

#include "cc_tools_qt/ToolsProtocol.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace plugin
{

class Protocol_CC_MQTT_SN : public cc_tools_qt::ToolsProtocol
{
    using Base = cc_tools_qt::ToolsProtocol;
public:
    Protocol_CC_MQTT_SN();
    virtual ~Protocol_CC_MQTT_SN();

protected:
    virtual const QString& nameImpl() const override;
};

} // namespace plugin

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
