// Generated by commsdsl2tools_qt v7.3.0

#pragma once

#include "cc_mqttsn/Version.h"
#include "cc_tools_qt/version.h"

#define CC_TOOLS_QT_PLUGIN_CC_MQTTSN_SPEC_VERSION (0)

static_assert(CC_TOOLS_QT_PLUGIN_CC_MQTTSN_SPEC_VERSION == CC_MQTTSN_SPEC_VERSION,
    "The spec versions don't match");

#define CC_TOOLS_QT_PLUGIN_CC_MQTTSN_MAJOR_VERSION (3)

#define CC_TOOLS_QT_PLUGIN_CC_MQTTSN_MINOR_VERSION (0)

#define CC_TOOLS_QT_PLUGIN_CC_MQTTSN_PATCH_VERSION (4)

#define CC_TOOLS_QT_PLUGIN_CC_MQTTSN_VERSION (COMMS_MAKE_VERSION(CC_MQTTSN_MAJOR_VERSION, CC_MQTTSN_MINOR_VERSION, CC_MQTTSN_PATCH_VERSION))

static_assert(CC_TOOLS_QT_PLUGIN_CC_MQTTSN_VERSION == CC_MQTTSN_VERSION, "Versions mismatch");

static_assert(CC_TOOLS_QT_MAKE_VERSION(6, 0, 5) <= cc_tools_qt::version(),
    "The version of cc_tools_qt library is too old");
