// Generated by commsdsl2tools_qt v7.1.0

#pragma once

#include "cc_mqttsn/Message.h"
#include "cc_tools_qt/ToolsMessage.h"
#include "cc_tools_qt/ToolsProtMsgInterface.h"
#include "cc_tools_qt_plugin/cc_mqttsn/Version.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

class Message : public cc_tools_qt::ToolsMessage
{
public:
    using ProtInterface = cc_tools_qt::ToolsProtMsgInterface<::cc_mqttsn::Message>;
    using ProtOptions = cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions;
    Message();
    virtual ~Message() noexcept;

protected:
    virtual QString idAsStringImpl() const override;
};

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
