// Generated by commsdsl2tools_qt v8.0.0

#pragma once

#include "cc_tools_qt/ToolsMsgFactory.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace factory
{

class MsgFactory : public cc_tools_qt::ToolsMsgFactory
{
public:
    MsgFactory();
    virtual ~MsgFactory();

protected:
    virtual MessagesListInternal createAllMessagesImpl() override;
};

} // namespace factory

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
