// Generated by commsdsl2tools_qt v7.0.3

#pragma once

#include <tuple>
#include "cc_mqttsn/frame/Frame.h"
#include "cc_tools_qt/ToolsTransportProtMessageBase.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace frame
{

template <typename TOpt>
struct FrameProtTransportMessageFields
{
    using All =
        std::tuple<
            ::cc_mqttsn::field::MsgLengthField<TOpt>,
            ::cc_mqttsn::field::MsgId<TOpt>,
            typename ::cc_mqttsn::frame::FrameLayers<TOpt>::Data::Field
        >;
};

template <typename TMsgBase, typename TOpt>
class FrameProtTransportMessage : public
    cc_tools_qt::ToolsTransportProtMessageBase<
        TMsgBase,
        typename FrameProtTransportMessageFields<TOpt>::All,
        FrameProtTransportMessage<TMsgBase, TOpt>
    >
{
    using Base =
        cc_tools_qt::ToolsTransportProtMessageBase<
            TMsgBase,
            typename FrameProtTransportMessageFields<TOpt>::All,
            FrameProtTransportMessage<TMsgBase, TOpt>
        >;
public:
    COMMS_MSG_FIELDS_NAMES(
        length,
        id,
        data
    );
};

} // namespace frame

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
