// Generated by commsdsl2tools_qt v6.3.3

#include "Advertise.h"

#include "cc_mqttsn/message/Advertise.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/Duration.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/GwId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_gwId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::AdvertiseFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::GwId;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_gwId(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_duration(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::AdvertiseFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Duration;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_duration(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_gwId(false));
    props.append(createProps_duration(false));
    return props;
}

} // namespace

class AdvertiseImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Advertise<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        AdvertiseImpl
    >
{
public:
    AdvertiseImpl() = default;
    AdvertiseImpl(const AdvertiseImpl&) = delete;
    AdvertiseImpl(AdvertiseImpl&&) = delete;
    virtual ~AdvertiseImpl() = default;
    AdvertiseImpl& operator=(const AdvertiseImpl&) = default;
    AdvertiseImpl& operator=(AdvertiseImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Advertise::Advertise() : m_pImpl(new AdvertiseImpl) {}
Advertise::~Advertise() = default;

Advertise& Advertise::operator=(const Advertise& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Advertise& Advertise::operator=(Advertise&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Advertise::MsgIdParamType Advertise::doGetId()
{
    return ::cc_mqttsn::message::Advertise<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Advertise::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Advertise::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Advertise::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Advertise::resetImpl()
{
    m_pImpl->reset();
}

bool Advertise::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Advertise*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Advertise::MsgIdParamType Advertise::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Advertise::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Advertise::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Advertise::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Advertise::lengthImpl() const
{
    return m_pImpl->length();
}

bool Advertise::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
