// Generated by commsdsl2tools_qt v6.3.3

#include "Fwd.h"

#include "cc_mqttsn/message/Fwd.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/Ctrl.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/NodeId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_ctrl(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::FwdFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Ctrl;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_ctrl(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_nodeId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::FwdFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::NodeId;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_nodeId(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_ctrl(false));
    props.append(createProps_nodeId(false));
    return props;
}

} // namespace

class FwdImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Fwd<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        FwdImpl
    >
{
public:
    FwdImpl() = default;
    FwdImpl(const FwdImpl&) = delete;
    FwdImpl(FwdImpl&&) = delete;
    virtual ~FwdImpl() = default;
    FwdImpl& operator=(const FwdImpl&) = default;
    FwdImpl& operator=(FwdImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Fwd::Fwd() : m_pImpl(new FwdImpl) {}
Fwd::~Fwd() = default;

Fwd& Fwd::operator=(const Fwd& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Fwd& Fwd::operator=(Fwd&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Fwd::MsgIdParamType Fwd::doGetId()
{
    return ::cc_mqttsn::message::Fwd<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Fwd::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Fwd::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Fwd::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Fwd::resetImpl()
{
    m_pImpl->reset();
}

bool Fwd::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Fwd*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Fwd::MsgIdParamType Fwd::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Fwd::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Fwd::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Fwd::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Fwd::lengthImpl() const
{
    return m_pImpl->length();
}

bool Fwd::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
