// Generated by commsdsl2tools_qt v6.3.3

#include "Pingreq.h"

#include "cc_mqttsn/message/Pingreq.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/ClientId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_clientId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::PingreqFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::ClientId;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_clientId(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_clientId(false));
    return props;
}

} // namespace

class PingreqImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Pingreq<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        PingreqImpl
    >
{
public:
    PingreqImpl() = default;
    PingreqImpl(const PingreqImpl&) = delete;
    PingreqImpl(PingreqImpl&&) = delete;
    virtual ~PingreqImpl() = default;
    PingreqImpl& operator=(const PingreqImpl&) = default;
    PingreqImpl& operator=(PingreqImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Pingreq::Pingreq() : m_pImpl(new PingreqImpl) {}
Pingreq::~Pingreq() = default;

Pingreq& Pingreq::operator=(const Pingreq& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Pingreq& Pingreq::operator=(Pingreq&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Pingreq::MsgIdParamType Pingreq::doGetId()
{
    return ::cc_mqttsn::message::Pingreq<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Pingreq::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Pingreq::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Pingreq::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Pingreq::resetImpl()
{
    m_pImpl->reset();
}

bool Pingreq::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Pingreq*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Pingreq::MsgIdParamType Pingreq::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Pingreq::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Pingreq::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Pingreq::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Pingreq::lengthImpl() const
{
    return m_pImpl->length();
}

bool Pingreq::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
