// Generated by commsdsl2tools_qt v6.3.2

#include "Register.h"

#include "cc_mqttsn/message/Register.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/MessageId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/TopicId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/TopicName.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_topicId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::RegisterFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::TopicId;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_topicId(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_msgId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::RegisterFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::MsgId;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_messageId(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_topicName(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::RegisterFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::TopicName;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_topicName(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_topicId(false));
    props.append(createProps_msgId(false));
    props.append(createProps_topicName(false));
    return props;
}

} // namespace

class RegisterImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Register<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        RegisterImpl
    >
{
public:
    RegisterImpl() = default;
    RegisterImpl(const RegisterImpl&) = delete;
    RegisterImpl(RegisterImpl&&) = delete;
    virtual ~RegisterImpl() = default;
    RegisterImpl& operator=(const RegisterImpl&) = default;
    RegisterImpl& operator=(RegisterImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Register::Register() : m_pImpl(new RegisterImpl) {}
Register::~Register() = default;

Register& Register::operator=(const Register& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Register& Register::operator=(Register&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Register::MsgIdParamType Register::doGetId()
{
    return ::cc_mqttsn::message::Register<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Register::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Register::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Register::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Register::resetImpl()
{
    m_pImpl->reset();
}

bool Register::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Register*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Register::MsgIdParamType Register::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Register::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Register::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Register::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Register::lengthImpl() const
{
    return m_pImpl->length();
}

bool Register::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
