// Generated by commsdsl2tools_qt v6.3.3

#include "Searchgw.h"

#include "cc_mqttsn/message/Searchgw.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/Radius.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_radius(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::SearchgwFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Radius;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_radius(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_radius(false));
    return props;
}

} // namespace

class SearchgwImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Searchgw<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        SearchgwImpl
    >
{
public:
    SearchgwImpl() = default;
    SearchgwImpl(const SearchgwImpl&) = delete;
    SearchgwImpl(SearchgwImpl&&) = delete;
    virtual ~SearchgwImpl() = default;
    SearchgwImpl& operator=(const SearchgwImpl&) = default;
    SearchgwImpl& operator=(SearchgwImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Searchgw::Searchgw() : m_pImpl(new SearchgwImpl) {}
Searchgw::~Searchgw() = default;

Searchgw& Searchgw::operator=(const Searchgw& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Searchgw& Searchgw::operator=(Searchgw&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Searchgw::MsgIdParamType Searchgw::doGetId()
{
    return ::cc_mqttsn::message::Searchgw<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Searchgw::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Searchgw::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Searchgw::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Searchgw::resetImpl()
{
    m_pImpl->reset();
}

bool Searchgw::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Searchgw*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Searchgw::MsgIdParamType Searchgw::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Searchgw::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Searchgw::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Searchgw::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Searchgw::lengthImpl() const
{
    return m_pImpl->length();
}

bool Searchgw::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
