// Generated by commsdsl2tools_qt v6.3.2

#include "Unsubscribe.h"

#include "cc_mqttsn/message/Unsubscribe.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/Flags.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/MessageId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/TopicId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/TopicName.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_flags(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::UnsubscribeFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Flags;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_flags(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_msgId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::UnsubscribeFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::MsgId;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_messageId(Field::name(), serHidden);
    return props;
}

struct TopicIdMembers
{
    static QVariantMap createProps_topicId(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_mqttsn::message::UnsubscribeFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::TopicIdMembers::TopicId;
        auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_topicId(Field::name(), serHidden);
        return props;
    }
}; // struct TopicIdMembers

static QVariantMap createProps_topicId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::UnsubscribeFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::TopicId;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .uncheckable()
            .field(TopicIdMembers::createProps_topicId(serHidden))
            .asMap();
}

struct TopicNameMembers
{
    static QVariantMap createProps_topicName(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_mqttsn::message::UnsubscribeFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::TopicNameMembers::TopicName;
        auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_topicName(Field::name(), serHidden);
        return props;
    }
}; // struct TopicNameMembers

static QVariantMap createProps_topicName(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::UnsubscribeFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::TopicName;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .uncheckable()
            .field(TopicNameMembers::createProps_topicName(serHidden))
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_flags(false));
    props.append(createProps_msgId(false));
    props.append(createProps_topicId(false));
    props.append(createProps_topicName(false));
    return props;
}

} // namespace

class UnsubscribeImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Unsubscribe<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        UnsubscribeImpl
    >
{
public:
    UnsubscribeImpl() = default;
    UnsubscribeImpl(const UnsubscribeImpl&) = delete;
    UnsubscribeImpl(UnsubscribeImpl&&) = delete;
    virtual ~UnsubscribeImpl() = default;
    UnsubscribeImpl& operator=(const UnsubscribeImpl&) = default;
    UnsubscribeImpl& operator=(UnsubscribeImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Unsubscribe::Unsubscribe() : m_pImpl(new UnsubscribeImpl) {}
Unsubscribe::~Unsubscribe() = default;

Unsubscribe& Unsubscribe::operator=(const Unsubscribe& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Unsubscribe& Unsubscribe::operator=(Unsubscribe&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Unsubscribe::MsgIdParamType Unsubscribe::doGetId()
{
    return ::cc_mqttsn::message::Unsubscribe<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Unsubscribe::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Unsubscribe::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Unsubscribe::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Unsubscribe::resetImpl()
{
    m_pImpl->reset();
}

bool Unsubscribe::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Unsubscribe*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Unsubscribe::MsgIdParamType Unsubscribe::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Unsubscribe::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Unsubscribe::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Unsubscribe::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Unsubscribe::lengthImpl() const
{
    return m_pImpl->length();
}

bool Unsubscribe::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
