// Generated by commsdsl2tools_qt v6.3.0

#include "Willmsgupd.h"

#include "cc_mqttsn/message/Willmsgupd.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/WillMsg.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_willMsg(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::WillmsgupdFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::WillMsg;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_willMsg(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_willMsg(false));
    return props;
}

} // namespace

class WillmsgupdImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Willmsgupd<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        WillmsgupdImpl
    >
{
public:
    WillmsgupdImpl() = default;
    WillmsgupdImpl(const WillmsgupdImpl&) = delete;
    WillmsgupdImpl(WillmsgupdImpl&&) = delete;
    virtual ~WillmsgupdImpl() = default;
    WillmsgupdImpl& operator=(const WillmsgupdImpl&) = default;
    WillmsgupdImpl& operator=(WillmsgupdImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Willmsgupd::Willmsgupd() : m_pImpl(new WillmsgupdImpl) {}
Willmsgupd::~Willmsgupd() = default;

Willmsgupd& Willmsgupd::operator=(const Willmsgupd& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Willmsgupd& Willmsgupd::operator=(Willmsgupd&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Willmsgupd::MsgIdParamType Willmsgupd::doGetId()
{
    return ::cc_mqttsn::message::Willmsgupd<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Willmsgupd::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Willmsgupd::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Willmsgupd::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Willmsgupd::resetImpl()
{
    m_pImpl->reset();
}

bool Willmsgupd::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Willmsgupd*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Willmsgupd::MsgIdParamType Willmsgupd::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Willmsgupd::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Willmsgupd::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Willmsgupd::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Willmsgupd::lengthImpl() const
{
    return m_pImpl->length();
}

bool Willmsgupd::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
