// Generated by commsdsl2tools_qt v6.3.3

#include "Willmsgresp.h"

#include "cc_mqttsn/message/Willmsgresp.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/ReturnCode.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

static QVariantMap createProps_returnCode(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::WillmsgrespFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::ReturnCode;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_returnCode(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_returnCode(false));
    return props;
}

} // namespace

class WillmsgrespImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Willmsgresp<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        WillmsgrespImpl
    >
{
public:
    WillmsgrespImpl() = default;
    WillmsgrespImpl(const WillmsgrespImpl&) = delete;
    WillmsgrespImpl(WillmsgrespImpl&&) = delete;
    virtual ~WillmsgrespImpl() = default;
    WillmsgrespImpl& operator=(const WillmsgrespImpl&) = default;
    WillmsgrespImpl& operator=(WillmsgrespImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Willmsgresp::Willmsgresp() : m_pImpl(new WillmsgrespImpl) {}
Willmsgresp::~Willmsgresp() = default;

Willmsgresp& Willmsgresp::operator=(const Willmsgresp& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Willmsgresp& Willmsgresp::operator=(Willmsgresp&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Willmsgresp::MsgIdParamType Willmsgresp::doGetId()
{
    return ::cc_mqttsn::message::Willmsgresp<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Willmsgresp::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Willmsgresp::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Willmsgresp::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Willmsgresp::resetImpl()
{
    m_pImpl->reset();
}

bool Willmsgresp::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Willmsgresp*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Willmsgresp::MsgIdParamType Willmsgresp::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Willmsgresp::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Willmsgresp::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Willmsgresp::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Willmsgresp::lengthImpl() const
{
    return m_pImpl->length();
}

bool Willmsgresp::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
