// Generated by commsdsl2tools_qt v6.3.3

#include "Willtopic.h"

#include "cc_mqttsn/message/Willtopic.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/Flags.h"
#include "cc_tools_qt_plugin/cc_mqttsn/field/WillTopic.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

struct FlagsMembers
{
    static QVariantMap createProps_flagsField(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_mqttsn::message::WilltopicFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::FlagsMembers::FlagsField;
        auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_flags(Field::name(), serHidden);
        return props;
    }
}; // struct FlagsMembers

static QVariantMap createProps_flags(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::WilltopicFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::Flags;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .field(FlagsMembers::createProps_flagsField(serHidden))
            .asMap();
}

static QVariantMap createProps_willTopic(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_mqttsn::message::WilltopicFields<cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::WillTopic;
    auto props = cc_tools_qt_plugin::cc_mqttsn::field::createProps_willTopic(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_flags(false));
    props.append(createProps_willTopic(false));
    return props;
}

} // namespace

class WilltopicImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Willtopic<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        WilltopicImpl
    >
{
public:
    WilltopicImpl() = default;
    WilltopicImpl(const WilltopicImpl&) = delete;
    WilltopicImpl(WilltopicImpl&&) = delete;
    virtual ~WilltopicImpl() = default;
    WilltopicImpl& operator=(const WilltopicImpl&) = default;
    WilltopicImpl& operator=(WilltopicImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Willtopic::Willtopic() : m_pImpl(new WilltopicImpl) {}
Willtopic::~Willtopic() = default;

Willtopic& Willtopic::operator=(const Willtopic& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Willtopic& Willtopic::operator=(Willtopic&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Willtopic::MsgIdParamType Willtopic::doGetId()
{
    return ::cc_mqttsn::message::Willtopic<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Willtopic::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Willtopic::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Willtopic::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Willtopic::resetImpl()
{
    m_pImpl->reset();
}

bool Willtopic::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Willtopic*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Willtopic::MsgIdParamType Willtopic::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Willtopic::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Willtopic::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Willtopic::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Willtopic::lengthImpl() const
{
    return m_pImpl->length();
}

bool Willtopic::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
