// Generated by commsdsl2tools_qt v6.3.0

#include "Willtopicreq.h"

#include "cc_mqttsn/message/Willtopicreq.h"
#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_mqttsn/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class WilltopicreqImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_mqttsn::message::Willtopicreq<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>,
        WilltopicreqImpl
    >
{
public:
    WilltopicreqImpl() = default;
    WilltopicreqImpl(const WilltopicreqImpl&) = delete;
    WilltopicreqImpl(WilltopicreqImpl&&) = delete;
    virtual ~WilltopicreqImpl() = default;
    WilltopicreqImpl& operator=(const WilltopicreqImpl&) = default;
    WilltopicreqImpl& operator=(WilltopicreqImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

Willtopicreq::Willtopicreq() : m_pImpl(new WilltopicreqImpl) {}
Willtopicreq::~Willtopicreq() = default;

Willtopicreq& Willtopicreq::operator=(const Willtopicreq& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Willtopicreq& Willtopicreq::operator=(Willtopicreq&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

Willtopicreq::MsgIdParamType Willtopicreq::doGetId()
{
    return ::cc_mqttsn::message::Willtopicreq<cc_tools_qt_plugin::cc_mqttsn::Message, cc_tools_qt_plugin::cc_mqttsn::options::DefaultOptions>::doGetId();
}

const char* Willtopicreq::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& Willtopicreq::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void Willtopicreq::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void Willtopicreq::resetImpl()
{
    m_pImpl->reset();
}

bool Willtopicreq::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const Willtopicreq*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

Willtopicreq::MsgIdParamType Willtopicreq::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus Willtopicreq::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus Willtopicreq::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool Willtopicreq::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t Willtopicreq::lengthImpl() const
{
    return m_pImpl->length();
}

bool Willtopicreq::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
