// Generated by commsdsl2tools_qt v8.0.0

/// @file
/// @brief Contains definition of the default options for plugin.

#pragma once

#include "cc_mqttsn/options/AllMessagesDynMemMsgFactoryDefaultOptions.h"
#include "cc_mqttsn/options/DefaultOptions.h"
#include "cc_tools_qt_plugin/cc_mqttsn/Version.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace options
{

using DefaultOptions =
    ::cc_mqttsn::options::AllMessagesDynMemMsgFactoryDefaultOptionsT<
        ::cc_mqttsn::options::DefaultOptions
    >;

} // namespace options

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
