// Generated by commsdsl2tools_qt v6.3.3

#include "cc_mqttsn/MsgId.h"
#include "cc_tools_qt_plugin/cc_mqttsn/factory/AllMessagesDynMemMsgFactory.h"
#include "cc_tools_qt_plugin/cc_mqttsn/input/AllMessages.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace factory
{

AllMessagesDynMemMsgFactory::MsgPtr AllMessagesDynMemMsgFactory::createMsg(MsgIdParamType id, unsigned idx, CreateFailureReason* reason) const
{
    auto updateReasonFunc =
        [reason](CreateFailureReason val)
        {
            if (reason != nullptr) {
                *reason = val;
            }
        };

    if (1U <= idx) {
        updateReasonFunc(CreateFailureReason::InvalidId);
        return MsgPtr();
    }

    updateReasonFunc(CreateFailureReason::None);
    switch (id) {
        case ::cc_mqttsn::MsgId_Advertise: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Advertise);
        case ::cc_mqttsn::MsgId_Searchgw: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Searchgw);
        case ::cc_mqttsn::MsgId_Gwinfo: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Gwinfo);
        case ::cc_mqttsn::MsgId_Connect: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Connect);
        case ::cc_mqttsn::MsgId_Connack: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Connack);
        case ::cc_mqttsn::MsgId_Willtopicreq: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willtopicreq);
        case ::cc_mqttsn::MsgId_Willtopic: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willtopic);
        case ::cc_mqttsn::MsgId_Willmsgreq: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willmsgreq);
        case ::cc_mqttsn::MsgId_Willmsg: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willmsg);
        case ::cc_mqttsn::MsgId_Register: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Register);
        case ::cc_mqttsn::MsgId_Regack: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Regack);
        case ::cc_mqttsn::MsgId_Publish: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Publish);
        case ::cc_mqttsn::MsgId_Puback: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Puback);
        case ::cc_mqttsn::MsgId_Pubcomp: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Pubcomp);
        case ::cc_mqttsn::MsgId_Pubrec: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Pubrec);
        case ::cc_mqttsn::MsgId_Pubrel: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Pubrel);
        case ::cc_mqttsn::MsgId_Subscribe: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Subscribe);
        case ::cc_mqttsn::MsgId_Suback: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Suback);
        case ::cc_mqttsn::MsgId_Unsubscribe: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Unsubscribe);
        case ::cc_mqttsn::MsgId_Unsuback: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Unsuback);
        case ::cc_mqttsn::MsgId_Pingreq: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Pingreq);
        case ::cc_mqttsn::MsgId_Pingresp: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Pingresp);
        case ::cc_mqttsn::MsgId_Disconnect: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Disconnect);
        case ::cc_mqttsn::MsgId_Willtopicupd: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willtopicupd);
        case ::cc_mqttsn::MsgId_Willtopicresp: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willtopicresp);
        case ::cc_mqttsn::MsgId_Willmsgupd: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willmsgupd);
        case ::cc_mqttsn::MsgId_Willmsgresp: return MsgPtr(new cc_tools_qt_plugin::cc_mqttsn::message::Willmsgresp);
        default: break;
    }

    updateReasonFunc(CreateFailureReason::InvalidId);
    return MsgPtr();
}

std::size_t AllMessagesDynMemMsgFactory::msgCount(MsgIdParamType id) const
{
    switch (id)
    {
        case ::cc_mqttsn::MsgId_Advertise: return 1U;
        case ::cc_mqttsn::MsgId_Searchgw: return 1U;
        case ::cc_mqttsn::MsgId_Gwinfo: return 1U;
        case ::cc_mqttsn::MsgId_Connect: return 1U;
        case ::cc_mqttsn::MsgId_Connack: return 1U;
        case ::cc_mqttsn::MsgId_Willtopicreq: return 1U;
        case ::cc_mqttsn::MsgId_Willtopic: return 1U;
        case ::cc_mqttsn::MsgId_Willmsgreq: return 1U;
        case ::cc_mqttsn::MsgId_Willmsg: return 1U;
        case ::cc_mqttsn::MsgId_Register: return 1U;
        case ::cc_mqttsn::MsgId_Regack: return 1U;
        case ::cc_mqttsn::MsgId_Publish: return 1U;
        case ::cc_mqttsn::MsgId_Puback: return 1U;
        case ::cc_mqttsn::MsgId_Pubcomp: return 1U;
        case ::cc_mqttsn::MsgId_Pubrec: return 1U;
        case ::cc_mqttsn::MsgId_Pubrel: return 1U;
        case ::cc_mqttsn::MsgId_Subscribe: return 1U;
        case ::cc_mqttsn::MsgId_Suback: return 1U;
        case ::cc_mqttsn::MsgId_Unsubscribe: return 1U;
        case ::cc_mqttsn::MsgId_Unsuback: return 1U;
        case ::cc_mqttsn::MsgId_Pingreq: return 1U;
        case ::cc_mqttsn::MsgId_Pingresp: return 1U;
        case ::cc_mqttsn::MsgId_Disconnect: return 1U;
        case ::cc_mqttsn::MsgId_Willtopicupd: return 1U;
        case ::cc_mqttsn::MsgId_Willtopicresp: return 1U;
        case ::cc_mqttsn::MsgId_Willmsgupd: return 1U;
        case ::cc_mqttsn::MsgId_Willmsgresp: return 1U;
        default: break;
    }

    return 0U;
}

} // namespace factory

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
