// Generated by commsdsl2tools_qt v6.3.0

#pragma once

#include <tuple>
#include "cc_tools_qt_plugin/cc_mqttsn/message/Advertise.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Connack.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Connect.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Disconnect.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Gwinfo.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Pingreq.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Pingresp.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Puback.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Pubcomp.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Publish.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Pubrec.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Pubrel.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Regack.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Register.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Searchgw.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Suback.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Subscribe.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Unsuback.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Unsubscribe.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willmsg.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willmsgreq.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willmsgresp.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willmsgupd.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willtopic.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willtopicreq.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willtopicresp.h"
#include "cc_tools_qt_plugin/cc_mqttsn/message/Willtopicupd.h"

namespace cc_tools_qt_plugin
{

namespace cc_mqttsn
{

namespace input
{

using AllMessages =
    std::tuple<
        cc_tools_qt_plugin::cc_mqttsn::message::Advertise,
        cc_tools_qt_plugin::cc_mqttsn::message::Searchgw,
        cc_tools_qt_plugin::cc_mqttsn::message::Gwinfo,
        cc_tools_qt_plugin::cc_mqttsn::message::Connect,
        cc_tools_qt_plugin::cc_mqttsn::message::Connack,
        cc_tools_qt_plugin::cc_mqttsn::message::Willtopicreq,
        cc_tools_qt_plugin::cc_mqttsn::message::Willtopic,
        cc_tools_qt_plugin::cc_mqttsn::message::Willmsgreq,
        cc_tools_qt_plugin::cc_mqttsn::message::Willmsg,
        cc_tools_qt_plugin::cc_mqttsn::message::Register,
        cc_tools_qt_plugin::cc_mqttsn::message::Regack,
        cc_tools_qt_plugin::cc_mqttsn::message::Publish,
        cc_tools_qt_plugin::cc_mqttsn::message::Puback,
        cc_tools_qt_plugin::cc_mqttsn::message::Pubcomp,
        cc_tools_qt_plugin::cc_mqttsn::message::Pubrec,
        cc_tools_qt_plugin::cc_mqttsn::message::Pubrel,
        cc_tools_qt_plugin::cc_mqttsn::message::Subscribe,
        cc_tools_qt_plugin::cc_mqttsn::message::Suback,
        cc_tools_qt_plugin::cc_mqttsn::message::Unsubscribe,
        cc_tools_qt_plugin::cc_mqttsn::message::Unsuback,
        cc_tools_qt_plugin::cc_mqttsn::message::Pingreq,
        cc_tools_qt_plugin::cc_mqttsn::message::Pingresp,
        cc_tools_qt_plugin::cc_mqttsn::message::Disconnect,
        cc_tools_qt_plugin::cc_mqttsn::message::Willtopicupd,
        cc_tools_qt_plugin::cc_mqttsn::message::Willtopicresp,
        cc_tools_qt_plugin::cc_mqttsn::message::Willmsgupd,
        cc_tools_qt_plugin::cc_mqttsn::message::Willmsgresp
    >;

} // namespace input

} // namespace cc_mqttsn

} // namespace cc_tools_qt_plugin
