// Generated by commsdsl2tools_qt v7.0.0

#include "Advertise.h"

#include "cc_mqttsn/message/Advertise.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class AdvertiseImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Advertise,
        AdvertiseImpl
    >
{
public:
    AdvertiseImpl() = default;
    AdvertiseImpl(const AdvertiseImpl&) = default;
    AdvertiseImpl(AdvertiseImpl&&) = default;
    virtual ~AdvertiseImpl() = default;
    AdvertiseImpl& operator=(const AdvertiseImpl&) = default;
    AdvertiseImpl& operator=(AdvertiseImpl&&) = default;
};

Advertise::Advertise() : m_pImpl(new AdvertiseImpl) {}
Advertise::~Advertise() = default;

Advertise& Advertise::operator=(const Advertise& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Advertise& Advertise::operator=(Advertise&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Advertise::nameImpl() const
{
    return m_pImpl->name();
}

bool Advertise::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Advertise::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Advertise::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Advertise::resetImpl()
{
    m_pImpl->reset();
}

bool Advertise::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Advertise*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Advertise::isValidImpl() const
{
    return m_pImpl->isValid();
}

Advertise::DataSeq Advertise::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Advertise::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Advertise::Ptr Advertise::cloneImpl() const
{
    ImplPtr impl(static_cast<AdvertiseImpl*>(m_pImpl->clone().release()));
    return Ptr(new Advertise(std::move(impl)));
}

void Advertise::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Advertise::DataSeq Advertise::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Advertise::FieldsList Advertise::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Advertise::FieldsList Advertise::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Advertise::Advertise(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
