// Generated by commsdsl2tools_qt v7.0.3

#include "Fwd.h"

#include "cc_mqttsn/message/Fwd.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class FwdImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Fwd,
        FwdImpl
    >
{
public:
    FwdImpl() = default;
    FwdImpl(const FwdImpl&) = default;
    FwdImpl(FwdImpl&&) = default;
    virtual ~FwdImpl() = default;
    FwdImpl& operator=(const FwdImpl&) = default;
    FwdImpl& operator=(FwdImpl&&) = default;
};

Fwd::Fwd() : m_pImpl(new FwdImpl) {}
Fwd::~Fwd() = default;

Fwd& Fwd::operator=(const Fwd& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Fwd& Fwd::operator=(Fwd&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Fwd::nameImpl() const
{
    return m_pImpl->name();
}

bool Fwd::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Fwd::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Fwd::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Fwd::resetImpl()
{
    m_pImpl->reset();
}

bool Fwd::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Fwd*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Fwd::isValidImpl() const
{
    return m_pImpl->isValid();
}

Fwd::DataSeq Fwd::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Fwd::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Fwd::Ptr Fwd::cloneImpl() const
{
    ImplPtr impl(static_cast<FwdImpl*>(m_pImpl->clone().release()));
    return Ptr(new Fwd(std::move(impl)));
}

void Fwd::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Fwd::DataSeq Fwd::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Fwd::FieldsList Fwd::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Fwd::FieldsList Fwd::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Fwd::Fwd(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
