// Generated by commsdsl2tools_qt v8.0.0

#include "Puback.h"

#include "cc_mqttsn/message/Puback.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class PubackImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Puback,
        PubackImpl
    >
{
public:
    PubackImpl() = default;
    PubackImpl(const PubackImpl&) = default;
    PubackImpl(PubackImpl&&) = default;
    virtual ~PubackImpl() = default;
    PubackImpl& operator=(const PubackImpl&) = default;
    PubackImpl& operator=(PubackImpl&&) = default;
};

Puback::Puback() : m_pImpl(new PubackImpl) {}
Puback::~Puback() = default;

Puback& Puback::operator=(const Puback& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Puback& Puback::operator=(Puback&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Puback::nameImpl() const
{
    return m_pImpl->name();
}

bool Puback::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Puback::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Puback::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Puback::resetImpl()
{
    m_pImpl->reset();
}

bool Puback::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Puback*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Puback::isValidImpl() const
{
    return m_pImpl->isValid();
}

Puback::DataSeq Puback::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Puback::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Puback::Ptr Puback::cloneImpl() const
{
    ImplPtr impl(static_cast<PubackImpl*>(m_pImpl->clone().release()));
    return Ptr(new Puback(std::move(impl)));
}

void Puback::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Puback::DataSeq Puback::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Puback::FieldsList Puback::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Puback::FieldsList Puback::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Puback::Puback(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
