// Generated by commsdsl2tools_qt v7.3.0

#include "Searchgw.h"

#include "cc_mqttsn/message/Searchgw.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class SearchgwImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Searchgw,
        SearchgwImpl
    >
{
public:
    SearchgwImpl() = default;
    SearchgwImpl(const SearchgwImpl&) = default;
    SearchgwImpl(SearchgwImpl&&) = default;
    virtual ~SearchgwImpl() = default;
    SearchgwImpl& operator=(const SearchgwImpl&) = default;
    SearchgwImpl& operator=(SearchgwImpl&&) = default;
};

Searchgw::Searchgw() : m_pImpl(new SearchgwImpl) {}
Searchgw::~Searchgw() = default;

Searchgw& Searchgw::operator=(const Searchgw& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Searchgw& Searchgw::operator=(Searchgw&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Searchgw::nameImpl() const
{
    return m_pImpl->name();
}

bool Searchgw::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Searchgw::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Searchgw::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Searchgw::resetImpl()
{
    m_pImpl->reset();
}

bool Searchgw::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Searchgw*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Searchgw::isValidImpl() const
{
    return m_pImpl->isValid();
}

Searchgw::DataSeq Searchgw::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Searchgw::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Searchgw::Ptr Searchgw::cloneImpl() const
{
    ImplPtr impl(static_cast<SearchgwImpl*>(m_pImpl->clone().release()));
    return Ptr(new Searchgw(std::move(impl)));
}

void Searchgw::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Searchgw::DataSeq Searchgw::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Searchgw::FieldsList Searchgw::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Searchgw::FieldsList Searchgw::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Searchgw::Searchgw(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
