// Generated by commsdsl2tools_qt v7.1.0

#include "Subscribe.h"

#include "cc_mqttsn/message/Subscribe.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class SubscribeImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Subscribe,
        SubscribeImpl
    >
{
public:
    SubscribeImpl() = default;
    SubscribeImpl(const SubscribeImpl&) = default;
    SubscribeImpl(SubscribeImpl&&) = default;
    virtual ~SubscribeImpl() = default;
    SubscribeImpl& operator=(const SubscribeImpl&) = default;
    SubscribeImpl& operator=(SubscribeImpl&&) = default;
};

Subscribe::Subscribe() : m_pImpl(new SubscribeImpl) {}
Subscribe::~Subscribe() = default;

Subscribe& Subscribe::operator=(const Subscribe& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Subscribe& Subscribe::operator=(Subscribe&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Subscribe::nameImpl() const
{
    return m_pImpl->name();
}

bool Subscribe::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Subscribe::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Subscribe::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Subscribe::resetImpl()
{
    m_pImpl->reset();
}

bool Subscribe::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Subscribe*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Subscribe::isValidImpl() const
{
    return m_pImpl->isValid();
}

Subscribe::DataSeq Subscribe::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Subscribe::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Subscribe::Ptr Subscribe::cloneImpl() const
{
    ImplPtr impl(static_cast<SubscribeImpl*>(m_pImpl->clone().release()));
    return Ptr(new Subscribe(std::move(impl)));
}

void Subscribe::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Subscribe::DataSeq Subscribe::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Subscribe::FieldsList Subscribe::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Subscribe::FieldsList Subscribe::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Subscribe::Subscribe(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
