// Generated by commsdsl2tools_qt v8.0.0

#include "Willmsgupd.h"

#include "cc_mqttsn/message/Willmsgupd.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class WillmsgupdImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Willmsgupd,
        WillmsgupdImpl
    >
{
public:
    WillmsgupdImpl() = default;
    WillmsgupdImpl(const WillmsgupdImpl&) = default;
    WillmsgupdImpl(WillmsgupdImpl&&) = default;
    virtual ~WillmsgupdImpl() = default;
    WillmsgupdImpl& operator=(const WillmsgupdImpl&) = default;
    WillmsgupdImpl& operator=(WillmsgupdImpl&&) = default;
};

Willmsgupd::Willmsgupd() : m_pImpl(new WillmsgupdImpl) {}
Willmsgupd::~Willmsgupd() = default;

Willmsgupd& Willmsgupd::operator=(const Willmsgupd& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Willmsgupd& Willmsgupd::operator=(Willmsgupd&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Willmsgupd::nameImpl() const
{
    return m_pImpl->name();
}

bool Willmsgupd::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Willmsgupd::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Willmsgupd::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Willmsgupd::resetImpl()
{
    m_pImpl->reset();
}

bool Willmsgupd::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Willmsgupd*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Willmsgupd::isValidImpl() const
{
    return m_pImpl->isValid();
}

Willmsgupd::DataSeq Willmsgupd::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Willmsgupd::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Willmsgupd::Ptr Willmsgupd::cloneImpl() const
{
    ImplPtr impl(static_cast<WillmsgupdImpl*>(m_pImpl->clone().release()));
    return Ptr(new Willmsgupd(std::move(impl)));
}

void Willmsgupd::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Willmsgupd::DataSeq Willmsgupd::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Willmsgupd::FieldsList Willmsgupd::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Willmsgupd::FieldsList Willmsgupd::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Willmsgupd::Willmsgupd(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
