// Generated by commsdsl2tools_qt v7.1.0

#include "Willmsgresp.h"

#include "cc_mqttsn/message/Willmsgresp.h"
#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_mqttsn/Message.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_mqttsn
{

namespace message
{

class WillmsgrespImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_mqttsn::Message,
        ::cc_mqttsn::message::Willmsgresp,
        WillmsgrespImpl
    >
{
public:
    WillmsgrespImpl() = default;
    WillmsgrespImpl(const WillmsgrespImpl&) = default;
    WillmsgrespImpl(WillmsgrespImpl&&) = default;
    virtual ~WillmsgrespImpl() = default;
    WillmsgrespImpl& operator=(const WillmsgrespImpl&) = default;
    WillmsgrespImpl& operator=(WillmsgrespImpl&&) = default;
};

Willmsgresp::Willmsgresp() : m_pImpl(new WillmsgrespImpl) {}
Willmsgresp::~Willmsgresp() = default;

Willmsgresp& Willmsgresp::operator=(const Willmsgresp& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

Willmsgresp& Willmsgresp::operator=(Willmsgresp&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* Willmsgresp::nameImpl() const
{
    return m_pImpl->name();
}

bool Willmsgresp::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong Willmsgresp::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString Willmsgresp::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void Willmsgresp::resetImpl()
{
    m_pImpl->reset();
}

bool Willmsgresp::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const Willmsgresp*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool Willmsgresp::isValidImpl() const
{
    return m_pImpl->isValid();
}

Willmsgresp::DataSeq Willmsgresp::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool Willmsgresp::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

Willmsgresp::Ptr Willmsgresp::cloneImpl() const
{
    ImplPtr impl(static_cast<WillmsgrespImpl*>(m_pImpl->clone().release()));
    return Ptr(new Willmsgresp(std::move(impl)));
}

void Willmsgresp::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

Willmsgresp::DataSeq Willmsgresp::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

Willmsgresp::FieldsList Willmsgresp::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

Willmsgresp::FieldsList Willmsgresp::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

Willmsgresp::Willmsgresp(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_mqttsn

} // namespace Message

} // namespace cc_tools_qt_plugin
